ENV_VAR_NAME__TS3_SERVER_IP = "TS3_SERVER_IP"
ENV_VAR_NAME__TS3_SERVER_PORT = "TS3_SERVER_PORT"
ENV_VAR_NAME__TS3_TELNET_LOGIN = "TS3_TELNET_LOGIN"
ENV_VAR_NAME__TS3_TELNET_PASSWORD = "TS3_TELNET_PASSWORD"
ENV_VAR_NAME__TS3_TELNET_PORT = "TS3_TELNET_PORT"

# Path: constants.py

BOT_CONFIG = {
    "name": "TS3Bot",
}
